name: Keep Render Service Alive

on:
  schedule:
    - cron: '*/14 * * * *' # Toutes les 14 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Services
        run: |
          curl -f -s https://coloringbook-frontend.onrender.com || echo "Frontend ping failed"
          curl -f -s https://coloringbook-backend.onrender.com || echo "Backend ping failed"